sudo: required
language: bash
script:
  - env
  - make check
deploy:
  provider: releases
  api_key:
    secure: liVmx/OrjLK067BbhcpV3x58SiqgqR4e6/GIFqzkRMfmL+ieB7jobKP6eDy/RP8SrVAGeMyTLnHJsU5EY7tFoE5qzEpLcEIxMF/Rl1tQy10gPEb308ByubgNeqw5wVTtPmrnczwvWlwLEtNY2zNC+NaLkgJPY/BP6DZSdzBg74v4LJgFVccWrdGlA0RiKPZ1XGdQ1eiDD+K+Qv+tH6YTLwpvXz4o8VADE7qlbNpH4nTPU+RFXD6qRq1aAJHXgl9YqhgtLN/mGb2rX2R2qf4WeQ7dntV16S5cBN8kD5YUJEHcHQQ4Lw8VATD8Vz3PwqdglSHPNZ9ouOgImaVnGB4UC3XUhGMDnJsqtNuFa4fca+EkkKKqJ6mHRSf49PV1+mJCEZq+b5t14eAhvIK3k1q+PU016bNvn16D3EfXFSu5SWW2Iid4gMiFsjL8uMoqhRU2Jvp7Wzb1qWwS7+KYd8CpVaI9zYogDnVR4QU1rBEx9iMjIXhZp8S04uczz8DxhNiLchFE20Olv/bkYWe8hewih6aeNBCSZxNDnaeU3Vxb5/eFm0Y6l8ZTwHLKWpftq5oFO7fVtLoPt0l3OyOMtzC34rGvSDJrbCwi2fNKPY3P6mxJIdlszLIkId6ccCB/c94CQN3X7jwkYz9jFGbwzy/hd+CsPKEYMrJaXvgoFBraTtU=
  file: zoostrap
  on:
    repo: guillon/zoostrap
    tags: true
