sudo: required
language: bash
script:
- env
- [ -n "$TRAVIS_TAG" ] || travis_wait 30 make check
deploy:
  provider: releases
  api_key:
    secure: xcJiV00mi8CjMUx2Bz+PReNUFIpEwRFIhWXcv7qn7oCkg0pxinYsWFg0nvd8ZAbZbJSfGT5bsCiVv8Mon6HDifiZTjNdYqk2l5IncbQv17wpm1b/UhQN3xmuSios24izX7Lf2wkroEVi+6DHzhgEgpmD11uNAtKrXYHm1wiIWpALzTiM+R+/h6XTxAYApf7dhlXFCWxzq0iJKBXud6gnKLZNYEvNyAS2RV/3AouEG828i9IVrubqolxO9dD71A1ZtuJ1JJ+dzQhSIQ7eUZvF01TGAFBeb+mKuhOFOjnZf7uz+R1U5gLHwzU8m2w57y+04/t67C0Q1xV/lQg3U9IkVmkjYK7nHnAClkZfg0mCqBKSMXO+iGSYryjRAAyQnz6QZlGYGPXrXLkFpx6xCyu3koxyU2fzmsLCvKVxaN+V/FnhRCc5kKtb22XbnEmFIArVpLkC9wfoo1OiEtq7wonRKZ+bQHcgsXaybWH0Ru4+CywRHL7fFcKs031k7hN+pd4snY78bdPUt1AYbB7SPuNJjY155cpoaAzMPe4EYsOqfyq4Ev03IOInZiT/5yp+UiyRPgtCDZIhPZYkrDSb+xFKULkuz+55xgjRgofcOvhjHGIy8Wro+D2y47v5t/n0rM6T52rChXnKJl6ys+VK17MGkQQ0E5Q89dkscj9ZC+ob8cE=
  file: zoostrap
  on:
    repo: guillon/zoostrap
    tags: true
