#!/usr/bin/env bash
#
# Copyright (c) STMicroelectronics 2015
#
# This file is part of zoostrap.
#
# zoostrap is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License v2.0
# as published by the Free Software Foundation
#
# zoostrap is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# v2.0 along with zoostrap. If not, see <http://www.gnu.org/licenses/>.
#

set -eu
set -o pipefail

basename=$(basename "$0")
dirname=$(readlink -e "$(dirname "$0")")

ZS_DISTRIB_ID="${ZS_DISTRIB_ID:-ubuntu}"
ZS_DISTRIB_RELEASE="${ZS_DISTRIB_RELEASE:-12.04}"
ZS_DISTRIB_PACKAGES="${ZS_DISTRIB_PACKAGES:-}"
ZS_UPDATE="${ZS_UPDATE:-true}"
ZS_UPGRADE="${ZS_UPGRADE:-false}"
ZS_R_BINDINGS="${ZS_R_BINDINGS:--b /etc/host.conf -b /etc/hosts -b /etc/hosts.equiv -b /etc/mtab -b /etc/netgroup -b /etc/networks -b /etc/passwd -b /etc/group -b /etc/nsswitch.conf -b  /etc/resolv.conf -b /etc/localtime -b /dev/ -b /sys/ -b /proc/ -b /tmp/ -b /run/}"
ZS_S_BINDINGS="${ZS_S_BINDINGS:--b /etc/host.conf -b /etc/hosts -b /etc/nsswitch.conf -b  /etc/resolv.conf -b /dev/ -b /sys/ -b /proc/ -b /tmp/ -b /run/shm/}"

ZS_WGET="${ZS_WGET:-wget --no-check-certificate --tries 3}"
DST_DIR="${1:-}"

ZS_CKAINS_URL="https://github.com/mickael-guene/ckains/releases/download/v1.1.0/ckains.x86_64"
ZS_CKAINS_SHA1SUM="90c454a4cef40f237eed8c2b2f63264a2079fa5e"
ZS_PROOT_URL="https://github.com/proot-me/proot-static-build/raw/master/static/proot-x86_64"
ZS_PROOT_SHA1SUM="5e713559fd336074971590e8cbe7ab1593ffabfc"

function error() { echo "$basename: error: $1" >&2; exit 1; }
function warning() { echo "$basename: warning: $1" >&2; }
function info() { echo "$basename: info: $1"; }
function cleanup() { local code=$?; trap - INT TERM QUIT EXIT; [ ! -d "${tmpdir:-}" ] || rm -rf "$tmpdir"; exit $code; }
trap cleanup INT TERM QUIT EXIT

ZS_DISTRIB_URL=""
case "${ZS_DISTRIB_ID}-${ZS_DISTRIB_RELEASE}" in
  ubuntu-12.04) \
    ZS_DISTRIB_URL="http://cdimage.ubuntu.com/ubuntu-core/releases/12.04/release/ubuntu-core-12.04.5-core-amd64.tar.gz"
    ZS_DISTRIB_SHA1SUM="10e690309ebeb2ab06d8faf40b0c08c0723c7639"
    ;;
  ubuntu-14.04) \
    ZS_DISTRIB_URL="http://cdimage.ubuntu.com/ubuntu-core/releases/14.04/release/ubuntu-core-14.04.2-core-amd64.tar.gz"
    ZS_DISTRIB_SHA1SUM="0993465651afdf4e2ea18af6d0b3233080f8d6f2"
    ;;
  centos-5) \
    ZS_DISTRIB_URL="https://github.com/CentOS/sig-cloud-instance-images/raw/c8d1a81b0516bca0f20434be8d0fac4f7d58a04a/docker/centos-5-20150304_1234-docker.tar.xz"
    ZS_DISTRIB_SHA1SUM="9b255140c44f4378aec44a77708ccaede7a14474"
# The centos 5 openvz image does not have yum installed, use docker image above
#    ZS_DISTRIB_URL="http://download.openvz.org/template/precreated/centos-5-x86_64.tar.gz"
#    ZS_DISTRIB_SHA1SUM="048763ea19416323a09ec94cee7e0cc859f284c2"
    ;;
  centos-6) \
    ZS_DISTRIB_URL="http://download.openvz.org/template/precreated/centos-6-x86_64-minimal.tar.gz"
    ZS_DISTRIB_SHA1SUM="47b773ca9d5b7fc33a7e7e2d711f14b3564a4db9"
    ;;
  centos-7) \
    ZS_DISTRIB_URL="http://download.openvz.org/template/precreated/centos-7-x86_64-minimal.tar.gz"
    ZS_DISTRIB_SHA1SUM="4277ccd7d363a97593fcd74614be43ad9aca6cac"
    ;;
  fedora-20) \
    ZS_DISTRIB_URL="https://github.com/fedora-cloud/docker-brew-fedora/raw/10ada29063147fde9e39190f4c2344b6e6e659e6/fedora-20-medium.tar.xz"
    ZS_DISTRIB_SHA1SUM="925fb62ffa06fca9d8175329a7a25d568a6d2569"
    ;;
  fedora-21) \
    ZS_DISTRIB_URL="https://github.com/fedora-cloud/docker-brew-fedora/raw/e32493b9601c3535cd6e0d0a8ff61d8fa95afb83/fedora-21-release.tar.xz"
    ZS_DISTRIB_SHA1SUM="cebddbab94c873187e030a5aaab807db46f1edd7"
    ;;
  fedora-22) \
    ZS_DISTRIB_URL="https://github.com/fedora-cloud/docker-brew-fedora/raw/e5a0a567230ca8350d2be9b100604858fc898c0b/fedora-22-release.tar.xz"
    ZS_DISTRIB_SHA1SUM="e0bdc85ba132391a39cae293db351a97f2ddbbcf"
    ;;
  fedora-23) \
    ZS_DISTRIB_URL="https://github.com/fedora-cloud/docker-brew-fedora/raw/a079b0713dca2db8bce3a07c9a2caae0e276bebf/fedora-23-20160104.tar.xz"
    ZS_DISTRIB_SHA1SUM="b7b550f387a604904d1d7ab0a194a92cb1007a59"
    ;;
esac
case "${ZS_DISTRIB_ID}-${ZS_DISTRIB_RELEASE}" in
  ubuntu-*) \
    ZS_DISTRIB_UPDATE="sed -i 's/# \(deb .*universe\)/\1/' /etc/apt/sources.list && apt-get update -qqy"
    ZS_DISTRIB_UPGRADE="apt-get upgrade -qqy"
    ZS_DISTRIB_INSTALL="apt-get install -qqy"
    ;;
  centos-*) \
    ZS_DISTRIB_UPDATE="rm -f /etc/yum.repos.d/vz.repo && yum update -y"
    ZS_DISTRIB_UPGRADE="true"
    ZS_DISTRIB_INSTALL="yum install -y"
    ;;
  fedora-20|fedora-21) \
    ZS_DISTRIB_UPDATE="yum update -y"
    ZS_DISTRIB_UPGRADE="true"
    ZS_DISTRIB_INSTALL="yum install -y"
    ;;
  fedora-*) \
    ZS_DISTRIB_UPDATE="dnf update -y"
    ZS_DISTRIB_UPGRADE="true"
    ZS_DISTRIB_INSTALL="dnf install -y"
    ;;
esac

[ -n "$ZS_DISTRIB_URL" ] || error "no default URL for $ZS_DISTRIB_ID-$ZS_DISTRIB_RELEASE"
[ -n "$DST_DIR" ] || error "missing dst_dir argument"
shift

if [ -d "$DST_DIR" ]; then
    info "Trashing former $DST_DIR..."
    dst_dir_dirname="$(dirname "$(readlink -e "$DST_DIR")")"
    trash_tmpdir="$(mktemp -d -p "$dst_dir_dirname" trash.zoostrap.XXXXXX)"
    chmod u+rwx "$DST_DIR"
    mv "$DST_DIR" "$trash_tmpdir"
fi

info "Creating $DST_DIR..."
mkdir -p "$DST_DIR"
dst_dir_dirname="$(dirname "$(readlink -e "$DST_DIR")")"

info "Cleaning trash dirs..."
chmod -R +rwX "$dst_dir_dirname"/trash.zoostrap.* 2>/dev/null || true
rm -rf "$dst_dir_dirname"/trash.zoostrap.* || warning "could not remove completly trash dirs when running: rm -rf $dst_dir_dirname/trash.zoostrap.*"

tmpdir="$(mktemp -d -p "$dst_dir_dirname" tmp.zoostrap.XXXXXX)"

info "Downloading ckains from $ZS_CKAINS_URL..."
$ZS_WGET -O "$tmpdir"/ckains "$ZS_CKAINS_URL" 2>"$tmpdir"/wget.log || error "failed to download ckains tool from $ZS_CKAINS_URL: error code $?: error log: $(<wget.log)"
echo "$ZS_CKAINS_SHA1SUM  $tmpdir/ckains" | sha1sum --check --status || error "invalid checksum (sha1sum) for $ZS_CKAINS_URL, expecting: $ZS_CKAINS_SHA1SUM"

info "Downloading proot from $ZS_PROOT_URL..."
$ZS_WGET -O "$tmpdir"/proot "$ZS_PROOT_URL" 2>"$tmpdir"/wget.log || error "failed to download ckains tool from $ZS_PROOT_URL:  error code $?: error log: $(<wget.log)"
echo "$ZS_PROOT_SHA1SUM  $tmpdir/proot" | sha1sum --check --status || error "invalid checksum (sha1sum) for $ZS_PROOT_URL, expecting: $ZS_PROOT_SHA1SUM"

distro_arch="$(basename "$ZS_DISTRIB_URL")"
info "Downloading image for $ZS_DISTRIB_ID-$ZS_DISTRIB_RELEASE from $ZS_DISTRIB_URL..."
$ZS_WGET -O "$tmpdir/$distro_arch" "$ZS_DISTRIB_URL" 2>"$tmpdir"/wget.log || error "failed to download image from $ZS_DISTRIB_URL:  error code $?: error log: $(<wget.log)"
echo "$ZS_DISTRIB_SHA1SUM  $tmpdir/$distro_arch" | sha1sum --check --status || warning "checksum (sha1sum) as changed for $ZS_DISTRIB_URL, expecting: $ZS_DISTRIB_SHA1SUM"

info "Extracting $ZS_DISTRIB_URL in $DST_DIR..."
case "$distro_arch" in
    *.tgz|*.tar.gz) \
        gzip -d - < "$tmpdir/$distro_arch" | tar xf - -C "$DST_DIR" 2>/dev/null || true
        ;;
    *.tar.xz) \
        xz -d - < "$tmpdir/$distro_arch" | tar xf - -C "$DST_DIR" 2>/dev/null || true
        ;;
    *.tar.bz2) \
        bzip2 -d - < "$tmpdir/$distro_arch" | tar xf - -C "$DST_DIR" 2>/dev/null || true
        ;;
    *) \
        error "unsupported archive type for image: $ZS_DISTRIB_URL"
        ;;
esac
chmod u+rwx "$DST_DIR"

mkdir -p "$DST_DIR"/.zoostrap
mv "$tmpdir"/ckains "$DST_DIR"/.zoostrap/ckains
chmod +x "$DST_DIR"/.zoostrap/ckains
mv "$tmpdir"/proot "$DST_DIR"/.zoostrap/proot
chmod +x "$DST_DIR"/.zoostrap/proot

cat >"$DST_DIR"/.zoostrap/run <<EOF
#!/bin/sh
dir="\`dirname "\$0"\`"
rootfs="\$dir/.."
is_dir_weak() { [ -e "\$1" ] || return 0; [ -d "\$1" ] || return 1; }
is_reg_weak() { [ -e "\$1" ] || return 0; [ -f "\$1" ] || return 1; [ ! -h "\$1" ] || return 1; }
bindings=""
for i in $ZS_R_BINDINGS; do
    case "\$i" in
    */) [ -d "\$i" ] && is_dir_weak "\$rootfs/\$i" && bindings="\$bindings -b \$i"
    ;;
    *)  [ -f "\$i" ] && is_reg_weak "\$rootfs/\$i" && bindings="\$bindings -b \$i"
    esac
done
for i in \`env -0 | tr -d '\n' | tr '\0' '\n' | sed 's/^\([^=]*\).*/\1/'\`; do
    case "\$i" in
    http_proxy|https_proxy|ftp_proxy|all_proxy|no_proxy) : ;;
    HTTP_PROXY|HTTPS_PROXY|FTP_PROXY|ALL_PROXY|NO_PROXY) : ;;
    *) unset "\$i" ;;
    esac
done
HOME=/nonexistent
export HOME
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export PATH
exec "\$dir"/ckains -r "\$rootfs" -w / \\
     \$bindings \\
     \${1+"\$@"}
EOF
chmod +x "$DST_DIR"/.zoostrap/run

cat >"$DST_DIR"/.zoostrap/srun <<EOF
#!/bin/sh
dir="\`dirname "\$0"\`"
rootfs="\$dir/.."
is_dir_weak() { [ -e "\$1" ] || return 0; [ -d "\$1" ] || return 1; }
is_reg_weak() { [ -e "\$1" ] || return 0; [ -f "\$1" ] || return 1; [ ! -h "\$1" ] || return 1; }
for i in $ZS_S_BINDINGS; do
    case "\$i" in
    */) [ -d "\$i" ] && is_dir_weak "\$rootfs/\$i" && bindings="\$bindings -b \$i"
    ;;
    *)  [ -f "\$i" ] && is_reg_weak "\$rootfs/\$i" && bindings="\$bindings -b \$i"
    esac
done
for i in \`env -0 | tr -d '\n' | tr '\0' '\n' | sed 's/^\([^=]*\).*/\1/'\`; do
    case "\$i" in
    http_proxy|https_proxy|ftp_proxy|all_proxy|no_proxy) : ;;
    HTTP_PROXY|HTTPS_PROXY|FTP_PROXY|ALL_PROXY|NO_PROXY) : ;;
    *) unset "\$i" ;;
    esac
done
HOME=/nonexistent
export HOME
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export PATH
exec "\$dir"/proot -0 -r "\$rootfs" -w / \\
     \$bindings \\
     \${1+"\$@"}
EOF
chmod +x "$DST_DIR"/.zoostrap/srun

info "Updating distro..."
if [ "$ZS_UPDATE" != false ]; then
  "$DST_DIR"/.zoostrap/srun sh -c "$ZS_DISTRIB_UPDATE" || true
else
  info "Skipped (ZS_UPDATE=$ZS_UPDATE)."
fi

info "Upgrading distro..."
if [ "$ZS_UPGRADE" != false ]; then
  "$DST_DIR"/.zoostrap/srun sh -c "$ZS_DISTRIB_UPGRADE" || true
else
  info "Skipped (ZS_UPGRADE=$ZS_UPGRADE)."
fi

info "Installing packages..."
if [ -n "$ZS_DISTRIB_PACKAGES" ]; then
  info "Requested packages: $ZS_DISTRIB_PACKAGES..."
  "$DST_DIR"/.zoostrap/srun sh -c "$ZS_DISTRIB_INSTALL $ZS_DISTRIB_PACKAGES" || true
else
  info "Skipped, no package requested (ZS_DISTRIB_PACKAGES=$ZS_DISTRIB_PACKAGES)."
fi

if [ "${1+1}" = 1 ]; then
  info "Executing command: ${1+$@}"
  "$DST_DIR"/.zoostrap/run ${1+"$@"}
fi
