#!/usr/bin/env bash
#
# Copyright (c) STMicroelectronics 2015
#
# This file is part of zoostrap.
#
# zoostrap is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License v2.0
# as published by the Free Software Foundation
#
# zoostrap is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# v2.0 along with zoostrap. If not, see <http://www.gnu.org/licenses/>.
#

set -eu
set -o pipefail

dirname="$(dirname "$(readlink -e "$0")")"
basename="$(basename "$0")"

# Change whenever generated rootfs may have different content
# with same zoostrap command args.
# Used to differentiate cached rootfs when ZS_BCACHE == true.
ZS_ID="1.2"

ZS_DISTRIB_ID="${ZS_DISTRIB_ID:-ubuntu}"
ZS_DISTRIB_RELEASE="${ZS_DISTRIB_RELEASE:-12.04}"
ZS_DISTRIB_ARCH="${ZS_DISTRIB_ARCH:-$(uname -m)}"
ZS_DISTRIB_PACKAGES="${ZS_DISTRIB_PACKAGES:-}"
ZS_PACKAGES_STRICT="${ZS_PACKAGES_STRICT:-true}"
ZS_UPDATE="${ZS_UPDATE:-true}"
ZS_UPDATE_STRICT="${ZS_UPDATE_STRICT:-true}"
ZS_UPGRADE="${ZS_UPGRADE:-false}"
ZS_UPGRADE_STRICT="${ZS_UPGRADE_STRICT:-true}"
ZS_R_BINDINGS="${ZS_R_BINDINGS:-/etc/host.conf /etc/hosts /etc/hosts.equiv /etc/mtab /etc/netgroup /etc/networks /etc/passwd /etc/group /etc/nsswitch.conf  /etc/resolv.conf /etc/localtime /dev/ /sys/ /proc/ /tmp/ /run/}"
ZS_S_BINDINGS="${ZS_S_BINDINGS:-/etc/host.conf /etc/hosts /etc/nsswitch.conf  /etc/resolv.conf /dev/ /sys/ /proc/ /tmp/ /run/shm/}"

ZS_WGET="${ZS_WGET:-wget --no-check-certificate --timeout=30 --tries=2}"
ZS_CACHE_DIR="${ZS_CACHE_DIR-${HOME:+$HOME/.zoostrap}}"
ZS_DL_DIR="${ZS_CACHE_DIR:+$ZS_CACHE_DIR/downloads}"
ZS_BCACHE="${ZS_BCACHE:-false}"
ZS_BCACHE_DIR="${ZS_BCACHE_DIR-${HOME:+$HOME/.bcache}}"
ZS_BCACHE_ID="${ZS_BCACHE_ID-}"

DST_DIR="${1:-}"

ZS_CKAINS_URL="https://github.com/mickael-guene/ckains/releases/download/v1.1.0/ckains.x86_64"
ZS_CKAINS_SHA1SUM="90c454a4cef40f237eed8c2b2f63264a2079fa5e"
ZS_PROOT_URL="https://github.com/guillon/PRoot/releases/download/v5.1.0-guillon-1/proot-x86_64"
ZS_PROOT_SHA1SUM="f2247bf30d4c0b587a4b5c9b094ece2ce568f90e"
ZS_BCACHE_URL="https://github.com/guillon/bcache/releases/download/v0.4.0/bcache"
ZS_BCACHE_SHA1SUM="c6107fe4bc99e999d709b179b1f6e05e418d1101"

function error() { echo "$basename: error: $1" >&2; exit 1; }
function warning() { echo "$basename: warning: $1" >&2; }
function info() { echo "$basename: info: $1"; }

declare -a tmp_files=()
function add_temp() {
    local tmp="${1?}"
    tmp_files+=("$tmp")
}
function cleanup() {
    local code=$?
    local tmp
    trap - INT TERM QUIT EXIT
    if [ "${#tmp_files[@]}" != 0 ]; then
        for tmp in "${tmp_files[@]}"; do
            [ ! -e "$tmp" ] || chmod -R +rwX "$tmp" 2>/dev/null || true
            [ ! -e "$tmp" ] || rm -rf "$tmp"
        done
    fi
    exit $code
}
trap cleanup INT TERM QUIT EXIT

function retry_when() {
    local match="${1?}"
    local log="${2?}"
    local -a tries="(0 8 16 32 64 64)"
    local delay
    local tmplog
    local res
    local count

    shift 2
    tmplog="$(mktemp -p "$tmpdir")"
    for delay in "${tries[@]}"; do
        if [ "$delay" != 0 ]; then
            info "will retry after $delay secs..."
            sleep "$delay"
        fi
        res=0
        if [ -n "$log" ]; then
            "$@" 2>&1 | tee "$tmplog" >"$log" || res="$?"
        else
            "$@" 2>&1 | tee "$tmplog" || res="$?"
        fi
        count="$(grep -i -c -- "$match" "$tmplog" || true)"
        [ "$count" != 0 ] || break
    done
    return "$res"
}

function download() {
    local dl_url="${1?}"
    local dl_name="${2?}"
    local output="${3?}"
    local dl_sha1sum="${4:-}"
    local dl_dir="${5:-}"
    local bname
    local cache_entry
    local tmpfile
    local tmplog
    local res

    info "Downloading $dl_name from $dl_url..."
    mkdir -p "$(dirname "$output")"
    if [ -n "$dl_sha1sum" ] && [ -n "$dl_dir" ]; then
        cache_entry="${dl_sha1sum::2}/${dl_sha1sum:2}"
        if [ -f "$dl_dir/$cache_entry/$dl_name" ]; then
            info "Get $dl_name from cache entry $dl_dir/$cache_entry/$dl_name"
            cp -Ta "$dl_dir/$cache_entry/$dl_name" "$output"
            return 0
        fi
        mkdir -p "$dl_dir"
        dl_dir="$(readlink -e "$dl_dir")"
        chmod 700 "$dl_dir"
        mkdir -p "$dl_dir/$cache_entry"
        tmpfile="$(mktemp -p "$dl_dir/$cache_entry")"
        add_temp "$tmpfile"
        tmplog="$(mktemp -p "$dl_dir/$cache_entry")"
        add_temp "$tmplog"
    else
        tmpfile="$(mktemp -p "$(dirname "$output")")"
        add_temp "$tmpfile"
        tmplog="$(mktemp -p "$(dirname "$output")")"
        add_temp "$tmplog"
    fi

    res=0
    retry_when "error 50[01234]" "$tmplog" $ZS_WGET -O "$tmpfile" "$dl_url" || res="$?"
    [ "$res" = 0 ] || error "could not download $dl_name from $dl_url: error code: $res: error log: $(<"$tmplog")"

    if [ -n "$dl_sha1sum" ]; then
        echo "$dl_sha1sum  $tmpfile" | sha1sum -c --quiet --status || \
            error "unexpected sha1sum for $dl_name at $dl_url, expected: $dl_sha1sum"
    fi

    if [ -n "$dl_sha1sum" ] && [ -n "$dl_dir" ]; then
        info "Store $dl_name to cache entry $dl_dir/$cache_entry/$dl_name"
        mv -Tf "$tmpfile" "$dl_dir/$cache_entry/$dl_name"
        cp -Ta "$dl_dir/$cache_entry/$dl_name" "$output"
    else
        mv -Tf "$tmpfile" "$output"
    fi
}

ZS_CKAINS_OPTS=""
ZS_PROOT_OPTS=""
case "$ZS_DISTRIB_ARCH" in
  x86|i[3456]86) \
    ZS_DISTRIB_ARCH=x86
    ZS_CKAINS_OPTS="${ZS_CKAINS_OPTS:+ }--32"
    ;;
  amd64|x86_64) \
    ZS_DISTRIB_ARCH=x86_64
    ;;
esac

ZS_DISTRIB_URL=""
ZS_DISTRIB_SHA1SUM=""
ZS_DISTRIB_PREPARE=""
case "${ZS_DISTRIB_ID}-${ZS_DISTRIB_RELEASE}-${ZS_DISTRIB_ARCH}" in
  ubuntu-12.04-x86_64) \
     ZS_DISTRIB_URL="https://download.openvz.org/template/precreated/ubuntu-12.04-x86_64-minimal.tar.gz"
     ZS_DISTRIB_SHA1SUM="" # openvz distros URL are updated, don't check
     ZS_DISTRIB_PREPARE=""
#    Deprecrated by ubuntu
#    ZS_DISTRIB_URL="http://cdimage.ubuntu.com/ubuntu-core/releases/12.04/release/ubuntu-core-12.04.5-core-amd64.tar.gz"
#    ZS_DISTRIB_SHA1SUM="10e690309ebeb2ab06d8faf40b0c08c0723c7639"
#    ZS_DISTRIB_PREPARE="sed -i 's/# \(deb .*universe\)/\1/' /etc/apt/sources.list"
    ;;
  ubuntu-12.04-x86) \
     ZS_DISTRIB_URL="https://download.openvz.org/template/precreated/ubuntu-12.04-x86-minimal.tar.gz"
     ZS_DISTRIB_SHA1SUM="" # openvz distros URL are updated, don't check
     ZS_DISTRIB_PREPARE=""
#    Deprecrated by ubuntu
#    ZS_DISTRIB_URL="http://cdimage.ubuntu.com/ubuntu-core/releases/12.04/release/ubuntu-core-12.04.5-core-i386.tar.gz"
#    ZS_DISTRIB_SHA1SUM="003f32a4bc1e1a78c1f284f5cbeefbc19e4ca638"
#    ZS_DISTRIB_PREPARE="sed -i 's/# \(deb .*universe\)/\1/' /etc/apt/sources.list"
    ;;
  ubuntu-14.04-x86_64) \
     ZS_DISTRIB_URL="https://download.openvz.org/template/precreated/ubuntu-14.04-x86_64-minimal.tar.gz"
     ZS_DISTRIB_SHA1SUM="" # openvz distros URL are updated, don't check
     ZS_DISTRIB_PREPARE=""
#    Deprecrated by ubuntu
#    ZS_DISTRIB_URL="http://cdimage.ubuntu.com/ubuntu-core/releases/14.04/release/ubuntu-core-14.04.4-core-amd64.tar.gz"
#    ZS_DISTRIB_SHA1SUM="a7a122e432851f2ae37d9b878e75713649d53bb2"
#    ZS_DISTRIB_PREPARE="sed -i 's/# \(deb .*universe\)/\1/' /etc/apt/sources.list"
    ;;
  ubuntu-14.04-x86) \
     ZS_DISTRIB_URL="https://download.openvz.org/template/precreated/ubuntu-14.04-x86-minimal.tar.gz"
     ZS_DISTRIB_SHA1SUM="" # openvz distros URL are updated, don't check
     ZS_DISTRIB_PREPARE=""
#    Deprecrated by ubuntu
#    ZS_DISTRIB_URL="http://cdimage.ubuntu.com/ubuntu-core/releases/14.04/release/ubuntu-core-14.04.4-core-i386.tar.gz"
#    ZS_DISTRIB_SHA1SUM="f46c85bee7ed3ca47873d587f51801eab4748327"
#    ZS_DISTRIB_PREPARE="sed -i 's/# \(deb .*universe\)/\1/' /etc/apt/sources.list"
    ;;
  centos-5-x86_64) \
    ZS_DISTRIB_URL="https://github.com/CentOS/sig-cloud-instance-images/raw/c8d1a81b0516bca0f20434be8d0fac4f7d58a04a/docker/centos-5-20150304_1234-docker.tar.xz"
    ZS_DISTRIB_SHA1SUM="9b255140c44f4378aec44a77708ccaede7a14474"
    ;;
  centos-5-x86) \
    ZS_DISTRIB_URL="https://download.openvz.org/template/precreated/centos-5-x86.tar.gz"
    ZS_DISTRIB_SHA1SUM="" # openvz distros URL are updated, don't check
    ZS_DISTRIB_PREPARE="rm -f /etc/yum.repos.d/vz.repo" # Don't fecth from OpenVZ repos
    ;;
  centos-6-x86_64) \
    ZS_DISTRIB_URL="https://github.com/CentOS/sig-cloud-instance-images/raw/20732d1bb34a9aba45c1c6f41576ed6bf3d8c619/docker/centos-6-root.tar.xz"
    ZS_DISTRIB_SHA1SUM="d5a8ad4c4cff457aa0580cfb8c1cac1702b971cd"
    ;;
  centos-6-x86) \
    ZS_DISTRIB_URL="https://download.openvz.org/template/precreated/centos-6-x86-minimal.tar.gz"
    ZS_DISTRIB_SHA1SUM="" # openvz distros URL are updated, don't check
    ZS_DISTRIB_PREPARE="rm -f /etc/yum.repos.d/vz.repo" # Don't fecth from OpenVZ repos
    ;;
  centos-7-x86_64) \
    ZS_DISTRIB_URL="https://github.com/CentOS/sig-cloud-instance-images/raw/e72a549845ecce5563d15e600f1e735a71095dcf/docker/c7-docker.tar.xz"
    ZS_DISTRIB_SHA1SUM="8a42a19464ae4e85f0ceda0876e65d90c36b3e67"
    ;;
  fedora-20-x86_64) \
    ZS_DISTRIB_URL="https://github.com/fedora-cloud/docker-brew-fedora/raw/10ada29063147fde9e39190f4c2344b6e6e659e6/fedora-20-medium.tar.xz"
    ZS_DISTRIB_SHA1SUM="925fb62ffa06fca9d8175329a7a25d568a6d2569"
    ;;
  fedora-20-x86) \
    ZS_DISTRIB_URL="https://download.openvz.org/template/precreated/fedora-20-x86.tar.gz"
    ZS_DISTRIB_SHA1SUM="" # openvz distros URL are updated, don't check
    ZS_DISTRIB_PREPARE="rm -f /etc/yum.repos.d/vz.repo" # Don't fecth from OpenVZ repos
    ;;
  fedora-21-x86_64) \
    ZS_DISTRIB_URL="https://github.com/fedora-cloud/docker-brew-fedora/raw/e32493b9601c3535cd6e0d0a8ff61d8fa95afb83/fedora-21-release.tar.xz"
    ZS_DISTRIB_SHA1SUM="cebddbab94c873187e030a5aaab807db46f1edd7"
    ;;
  fedora-22-x86_64) \
    ZS_DISTRIB_URL="https://github.com/fedora-cloud/docker-brew-fedora/raw/e5a0a567230ca8350d2be9b100604858fc898c0b/fedora-22-release.tar.xz"
    ZS_DISTRIB_SHA1SUM="e0bdc85ba132391a39cae293db351a97f2ddbbcf"
    ;;
  fedora-23-x86_64) \
    ZS_DISTRIB_URL="https://github.com/fedora-cloud/docker-brew-fedora/raw/a079b0713dca2db8bce3a07c9a2caae0e276bebf/fedora-23-20160104.tar.xz"
    ZS_DISTRIB_SHA1SUM="b7b550f387a604904d1d7ab0a194a92cb1007a59"
    ;;
esac

case "${ZS_DISTRIB_ID}-${ZS_DISTRIB_RELEASE}-${ZS_DISTRIB_ARCH}" in
  ubuntu-*) \
    ZS_DISTRIB_UPDATE="env DEBIAN_FRONTEND=noninteractive apt-get update -qqy"
    ZS_DISTRIB_UPGRADE="env DEBIAN_FRONTEND=noninteractive apt-get upgrade -qqy"
    ZS_DISTRIB_INSTALL="env DEBIAN_FRONTEND=noninteractive apt-get install -qqy"
    ;;
  centos-*) \
    ZS_DISTRIB_UPDATE="yum update -y"
    ZS_DISTRIB_UPGRADE="true"
    ZS_DISTRIB_INSTALL="yum install -y"
    ;;
  fedora-20-*|fedora-21-*) \
    ZS_DISTRIB_UPDATE="yum update -y"
    ZS_DISTRIB_UPGRADE="true"
    ZS_DISTRIB_INSTALL="yum install -y"
    ;;
  fedora-*) \
    ZS_DISTRIB_UPDATE="dnf update -y"
    ZS_DISTRIB_UPGRADE="true"
    ZS_DISTRIB_INSTALL="dnf install -y"
    ;;
esac

[ -n "$ZS_DISTRIB_URL" ] || error "wrong arguments: no distribution available for triplet (ZS_DISTRIB_ID,ZS_DISTRIB_RELEASE,ZS_DISTRIB_ARCH): ($ZS_DISTRIB_ID,$ZS_DISTRIB_RELEASE,$ZS_DISTRIB_ARCH)"
[ -n "$DST_DIR" ] || error "missing argument: the rootfs directory to create must be specified as first argument"
shift

if [ -d "$DST_DIR" ]; then
    info "Trashing former $DST_DIR..."
    dst_dir_dirname="$(dirname "$(readlink -e "$DST_DIR")")"
    trash_tmpdir="$(mktemp -d -p "$dst_dir_dirname" trash.zoostrap.XXXXXX)"
    chmod u+rwx "$DST_DIR"
    mv "$DST_DIR" "$trash_tmpdir"/
fi

info "Creating $DST_DIR..."
mkdir -p "$DST_DIR"
dst_dir_dirname="$(dirname "$(readlink -e "$DST_DIR")")"
dst_dir_basename="$(basename "$DST_DIR")"

info "Cleaning trash dirs..."
chmod -R +rwX "$dst_dir_dirname"/trash.zoostrap.* 2>/dev/null || true
rm -rf "$dst_dir_dirname"/trash.zoostrap.* || warning "could not remove completly trash dirs when running: rm -rf $dst_dir_dirname/trash.zoostrap.*"

tmpdir="$(mktemp -d -p "$dst_dir_dirname" tmp.zoostrap.XXXXXX)"
add_temp "$tmpdir"

if [ "$ZS_BCACHE" = true ] && [ -n "$ZS_BCACHE_DIR" ] && [ "$ZS_UPGRADE" = false ]; then
    download "$ZS_BCACHE_URL" bcache "$tmpdir"/bcache "$ZS_BCACHE_SHA1SUM" "$ZS_DL_DIR"
    chmod +x "$tmpdir"/bcache
    cp -Ta "$dirname/$basename" "$tmpdir"/zoostrap
    pushd "$tmpdir" >/dev/null
    ./bcache -d -c "$ZS_BCACHE_DIR" -o rootfs \
        --env ZS_DISTRIB_ID="$ZS_DISTRIB_ID" \
        --env ZS_DISTRIB_RELEASE="$ZS_DISTRIB_RELEASE" \
        --env ZS_DISTRIB_ARCH="$ZS_DISTRIB_ARCH" \
        --env ZS_DISTRIB_PACKAGES="$ZS_DISTRIB_PACKAGES" \
        --env ZS_UPDATE="$ZS_UPDATE" \
        --env ZS_UPGRADE="$ZS_UPGRADE" \
        --env ZS_R_BINDINGS="$ZS_R_BINDINGS" \
        --env ZS_S_BINDINGS="$ZS_S_BINDINGS" \
        --venv ZS_WGET \
        --env ZS_CACHE_DIR="" \
        --env ZS_BCACHE="false" \
        --env ZS_BCACHE_DIR="" \
        --env ZS_PACKAGES_STRICT="true" \
        --env ZS_UPDATE_STRICT="true" \
        --env ZS_UPGRADE_STRICT="true" \
        --id ZS_ID="$ZS_ID" \
        ${ZS_BCACHE_ID:+--id "ZS_USER_ID=$ZS_BCACHE_ID"} \
        ./zoostrap rootfs
    popd >/dev/null
    mv -Tf "$tmpdir"/rootfs "$DST_DIR"
    if [ "${1+1}" = 1 ]; then
        info "Executing command: $*"
        "$DST_DIR"/.zoostrap/run "$@"
    fi
    exit 0
fi

download "$ZS_CKAINS_URL" ckains "$tmpdir"/ckains "$ZS_CKAINS_SHA1SUM" "$ZS_DL_DIR"

download "$ZS_PROOT_URL" proot "$tmpdir"/proot "$ZS_PROOT_SHA1SUM" "$ZS_DL_DIR"

distro_arch="$(basename "$ZS_DISTRIB_URL")"
download "$ZS_DISTRIB_URL" "$distro_arch" "$tmpdir/$distro_arch" "$ZS_DISTRIB_SHA1SUM" "$ZS_DL_DIR"

info "Extracting $ZS_DISTRIB_URL in $DST_DIR..."
case "$distro_arch" in
    *.tgz|*.tar.gz) \
        gzip -d - < "$tmpdir/$distro_arch" | tar xf - -C "$DST_DIR" 2>/dev/null || true
        ;;
    *.tar.xz) \
        xz -d - < "$tmpdir/$distro_arch" | tar xf - -C "$DST_DIR" 2>/dev/null || true
        ;;
    *.tar.bz2) \
        bzip2 -d - < "$tmpdir/$distro_arch" | tar xf - -C "$DST_DIR" 2>/dev/null || true
        ;;
    *) \
        error "unsupported archive type for image: $ZS_DISTRIB_URL"
        ;;
esac
rm -f "$tmpdir/$distro_arch"
chmod u+rwx "$DST_DIR"

mkdir -p "$DST_DIR"/.zoostrap
mv -Tf "$tmpdir"/ckains "$DST_DIR"/.zoostrap/ckains
chmod +x "$DST_DIR"/.zoostrap/ckains
mv -Tf "$tmpdir"/proot "$DST_DIR"/.zoostrap/proot
chmod +x "$DST_DIR"/.zoostrap/proot

cat >"$DST_DIR"/.zoostrap/run <<EOF
#!/bin/sh
dir="\`dirname "\$0"\`"
rootfs="\$dir/.."
is_dir_weak() { [ ! -h "\$1" ] || return 1; [ -e "\$1" ] || return 0; [ -d "\$1" ] || return 1; }
is_reg_weak() { [ ! -h "\$1" ] || return 1; [ -e "\$1" ] || return 0; [ -f "\$1" ] || return 1; }
bindings=""
for i in $ZS_R_BINDINGS; do
    case "\$i" in
    */) [ -d "\$i" ] && is_dir_weak "\$rootfs/\$i" && bindings="\$bindings -b \$i"
    ;;
    *)  [ -f "\$i" ] && is_reg_weak "\$rootfs/\$i" && bindings="\$bindings -b \$i"
    esac
done
for i in \`env | sed 's/^\([^=]*\).*/\1/'\`; do
    eval "i=\$i"
    case "\$i" in
    http_proxy|https_proxy|ftp_proxy|all_proxy|no_proxy) : ;;
    HTTP_PROXY|HTTPS_PROXY|FTP_PROXY|ALL_PROXY|NO_PROXY) : ;;
    *) unset "\$i" ;;
    esac
done
HOME=/home/guest
export HOME
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export PATH
mkdir -p "\$rootfs\$HOME"
chmod 700 "\$rootfs\$HOME"
exec "\$dir"/ckains -r "\$rootfs" -w / \\
     $ZS_CKAINS_OPTS \\
     \$bindings \\
     \${1+"\$@"}
EOF
chmod +x "$DST_DIR"/.zoostrap/run

cat >"$DST_DIR"/.zoostrap/srun <<EOF
#!/bin/sh
dir="\`dirname "\$0"\`"
rootfs="\$dir/.."
is_dir_weak() { [ ! -h "\$1" ] || return 1; [ -e "\$1" ] || return 0; [ -d "\$1" ] || return 1; }
is_reg_weak() { [ ! -h "\$1" ] || return 1; [ -e "\$1" ] || return 0; [ -f "\$1" ] || return 1; }
bindings=""
for i in $ZS_S_BINDINGS; do
    case "\$i" in
    */) [ -d "\$i" ] && is_dir_weak "\$rootfs/\$i" && bindings="\$bindings -b \$i"
    ;;
    *)  [ -f "\$i" ] && is_reg_weak "\$rootfs/\$i" && bindings="\$bindings -b \$i"
    esac
done
for i in \`env | sed 's/^\([^=]*\).*/\1/'\`; do
    eval "i=\$i"
    case "\$i" in
    http_proxy|https_proxy|ftp_proxy|all_proxy|no_proxy) : ;;
    HTTP_PROXY|HTTPS_PROXY|FTP_PROXY|ALL_PROXY|NO_PROXY) : ;;
    *) unset "\$i" ;;
    esac
done
HOME=/root
export HOME
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export PATH
exec "\$dir"/proot --kill-on-exit -0 -r "\$rootfs" -w / \\
     $ZS_PROOT_OPTS \\
     \$bindings \\
     \${1+"\$@"}
EOF
chmod +x "$DST_DIR"/.zoostrap/srun

info "Preparing distro..."
if [ -n "$ZS_DISTRIB_PREPARE" ]; then
  "$DST_DIR"/.zoostrap/srun sh -c "$ZS_DISTRIB_PREPARE"
fi

info "Updating distro..."
if [ "$ZS_UPDATE" != false ]; then
  res=0
  retry_when "\(error.* 50[01234]\|failed to fetch\)" "" "$DST_DIR"/.zoostrap/srun sh -c "$ZS_DISTRIB_UPDATE" || res="$?"
  [ "$ZS_UPDATE_STRICT" = false -o "$res" = 0 ] || exit "$res"
else
  info "Skipped (ZS_UPDATE='$ZS_UPDATE')."
fi

info "Upgrading distro..."
if [ "$ZS_UPGRADE" != false ]; then
  res=0
  retry_when "\(error.* 50[01234]\|failed to fetch\)" "" "$DST_DIR"/.zoostrap/srun sh -c "$ZS_DISTRIB_UPGRADE" || res="$?"
  [ "$ZS_UPGRADE_STRICT" = false -o "$res" = 0  ] || exit "$res"
else
  info "Skipped (ZS_UPGRADE='$ZS_UPGRADE')."
fi

info "Installing packages..."
if [ -n "$ZS_DISTRIB_PACKAGES" ]; then
  info "Requested packages: $ZS_DISTRIB_PACKAGES..."
  res=0
  retry_when "\(error.* 50[01234]\|failed to fetch\)" "" "$DST_DIR"/.zoostrap/srun sh -c "$ZS_DISTRIB_INSTALL $ZS_DISTRIB_PACKAGES" || res="$?"
  [ "$ZS_PACKAGES_STRICT" = false -o "$res" = 0  ] || exit "$res"
else
  info "Skipped, no package requested (ZS_DISTRIB_PACKAGES='$ZS_DISTRIB_PACKAGES')."
fi

if [ "${1+1}" = 1 ]; then
  info "Executing command: $*"
  "$DST_DIR"/.zoostrap/run "$@"
fi
